name: Build
on: [pull_request]

env:
  FORCE_COLOR: "1"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: ./packages/python/requirements.txt

      - run: python -m pip install -U pip setuptools wheel 
        working-directory: ./packages/python

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        working-directory: ./packages/python

      - run: python -m build
        working-directory: ./packages/python

permissions:
  contents: read
