"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python
        with:
          python-version: '3.11'

      # - run: python -m pip install -U pip setuptools wheel
      #   working-directory: ./packages/python

      # - name: Install dependencies
      #   run: python -m pip install -r requirements.txt
      #   working-directory: ./packages/python

      # - run: python -m build
      #   working-directory: ./packages/python

permissions:
  contents: read
