name: Lint
on: [pull_request]

env:
  FORCE_COLOR: "1"

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: ./packages/python/dev-deps/python3.11/lint.txt

      - run: pip install -U pip setuptools wheel 
        working-directory: ./packages/python

      - name: Install dependencies
        run: pip install -r dev-deps/python3.11/lint.txt
        working-directory: ./packages/python

      - run: ruff check .

permissions:
  contents: read
