on: [pull_request]

env:
  FORCE_COLOR: "1"

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ls

      # - uses: actions/setup-python
      #   with:
      #     python-version: '3.11'

      # - run: python -m pip install -U pip setuptools wheel
      #   working-directory: ./packages/python

      # - name: Install dependencies
      #   working-directory: ./packages/python
      #   run: pip install -r requirements.txt

      # - uses: pre-commit/action
      #   with:
      #     extra_args: --verbose

permissions:
  contents: read
