on: [pull_request]

env:
  FORCE_COLOR: "1"

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/actions/python-versions/blob/main/versions-manifest.json
          # - pyversion: "3.12"
          - pyversion: "3.11"
            enable_coverage: true
          - pyversion: "3.10"
            more_hypothesis_examples_if_cron: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyversion }}
          cache: pip
          cache-dependency-path: ./packages/python/requirements.txt

      - run: python -m pip install -U pip setuptools wheel 
        working-directory: ./packages/python

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        working-directory: ./packages/python

      - run: python -m pytest
        working-directory: ./packages/python

      - name: Upload coverage to Codecov  # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
        if: matrix.enable_coverage
        with:
          verbose: true
          files: ./packages/python/coverage.xml
          fail_ci_if_error: false  # https://github.com/codecov/codecov-action/issues/557

permissions:
  contents: read
