name: Release to PyPI

"on":
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip setuptools build
        working-directory: ./packages/python

      - run: python -m build
        working-directory: ./packages/python

      - name: Publish
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
        with:
          verbose: true
          packages-dir: ./packages/python/build

permissions:
  id-token: write
  contents: read
