# Listens for tag pushes
# On detection, automatically pushes to test pypi
# Then, cuts a release to Github.com
name: Release to Test PyPI

"on":
  workflow_dispatch:
  push:
    tags:
      # To publish a test release to test.pypi.org,
      # create and push a tag as follows:
      #     git tag -a 0.21.3.rc1 -m "Tag 0.21.3.rc1 for release to test.pypi.org"
      #     git push --tags
      # IMPORTANT: Run the following to clean up after:
      #     git tag -d 0.21.3.rc1
      #     git push origin :0.21.3.rc1
      - "[0-9]+.[0-9]+.[0-9]+.rc[0-9]+"



jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.11'
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: python -m pip install -U pip setuptools build
        working-directory: ./packages/python

      - run: make build_diagraph
        working-directory: ./packages/python

      - name: Publish
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
        with:
          packages-dir: ./packages/python/dist 
          verbose: true
          repository-url: https://test.pypi.org/legacy/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          # files: |
          #   LICENSE.txt
          #   *.jar

permissions:
  id-token: write
  contents: read
