# Listens for tag pushes
# On detection, automatically pushes to pypi
# Then, cuts a release to Github.com
name: Release to PyPI

"on":
  workflow_dispatch:
  push:
    tags:
      - "^[0-9]+.[0-9]+.[0-9]+$"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip setuptools build
        working-directory: ./packages/python

      - run: python -m build
        working-directory: ./packages/python

      - name: Publish
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
        with:
          verbose: true
          packages-dir: ./packages/python/dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          # files: |
          #   LICENSE.txt
          #   *.jar

permissions:
  id-token: write
  contents: read
