# Runs on pushes to the main branch. Whenever a difference in version is detected,
# this workflow automatically creates a new tag and pushes it, which
# should trigger subsequent actions.
name: Tag & Release
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check pypi versions
        uses: maybe-hello-world/pyproject-check-version@v3
        id: versioncheck
        with:
          pyproject-path: "./packages/python/pyproject.toml"    # default value

      - name: check output
        run: |
            echo "Output: ${{ steps.versioncheck.outputs.local_version_is_higher }}"  # 'true' or 'false
            echo "Local version: ${{ steps.versioncheck.outputs.local_version }}"     # e.g., 0.1.1
            echo "Public version: ${{ steps.versioncheck.outputs.public_version }}"   # e.g., 0.1.0

      - name: Tag new release
        if: "contains( steps.versioncheck.outputs.local_version_is_higher , 'true')"
        working-directory: ./packages/python
        run: |
              git config --global user.name 'Github Actions'
              git config --global user.email 'thekevinscott@users.noreply.github.com'
              git tag -a ${{ steps.versioncheck.outputs.local_version }} -m "Tag ${{ steps.versioncheck.outputs.local_version }} for release" && git push --tags
              python -m pip install -U pip setuptools build
              python -m build

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ steps.versioncheck.outputs.local_version }} =~ /[0-9]+.[0-9]+.[0-9]+.rc[0-9]+/ ]]; then
              echo "test_release=true" >> $GITHUB_OUTPUT
          fi

      - name: Check Test Release
        if: steps.check-tag.outputs.test_release == 'true'
        run: |
          echo "Is a test release"

      # - "[0-9]+.[0-9]+.[0-9]+.rc[0-9]+"
      # - "[0-9]+.[0-9]+.[0-9]+$"

      - name: Publish to Test Pypi
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
        if: "contains( steps.versioncheck.outputs.local_version_is_higher , 'true')"
        with:
          packages-dir: ./packages/python/dist
          verbose: true
          repository-url: https://test.pypi.org/legacy/

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: "contains( steps.versioncheck.outputs.local_version_is_higher , 'true')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          # files: |
          #   LICENSE.txt
          #   *.jar
          #
permissions:
  contents: write
  id-token: write
