# Runs on pushes to the main branch. Whenever a difference in version is detected,
# this workflow automatically creates a new tag and pushes it, which
# should trigger subsequent actions.
name: Tag
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check pypi versions
        uses: maybe-hello-world/pyproject-check-version@v3
        id: versioncheck
        with:
          pyproject-path: "./packages/python/pyproject.toml"    # default value

      - name: check output
        run: |
            echo "Output: ${{ steps.versioncheck.outputs.local_version_is_higher }}"  # 'true' or 'false
            echo "Local version: ${{ steps.versioncheck.outputs.local_version }}"     # e.g., 0.1.1
            echo "Public version: ${{ steps.versioncheck.outputs.public_version }}"   # e.g., 0.1.0

      - name: Do not tag
        if: "contains( steps.versioncheck.outputs.local_version_is_higher , 'false')"
        run: echo 'Do not need to tag'

      - name: Tag new release
        if: "contains( steps.versioncheck.outputs.local_version_is_higher , 'true')"
        run: |
              git config --global user.name 'Github Actions'
              git config --global user.email 'thekevinscott@users.noreply.github.com'
              git tag -a ${{ steps.versioncheck.outputs.local_version }} -m "Tag ${{ steps.versioncheck.outputs.local_version }} for release" && git push --tags
