name: Test

"on":
  workflow_dispatch:
  schedule:
    - cron: "15 16 * * *"
  push:
    branches:
      - main
      - dev
      - deps
  pull_request:
    branches:
      - main

env:
  FORCE_COLOR: "1"

jobs:
  test-all:
    name: ${{ matrix.pyversion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/actions/python-versions/blob/main/versions-manifest.json
          - pyversion: "3.12"
          - pyversion: "3.11"
            enable_coverage: true
          - pyversion: "3.10"
            more_hypothesis_examples_if_cron: true
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: ${{ matrix.pyversion }}
          cache: pip
          cache-dependency-path: dev-deps/${{ matrix.deps_subdir || format('python{0}', matrix.pyversion) }}/test.txt

      - run: python -m pip install -U pip setuptools wheel 
        working-directory: ./packages/python

      - run: python -m pip install -r requirements.txt
        working-directory: ./packages/python

      - run: python -m pytest
        working-directory: ./packages/python

      - name: Upload coverage to Codecov  # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
        if: matrix.enable_coverage
        with:
          verbose: true
          files: ./packages/python/coverage.xml
          fail_ci_if_error: false  # https://github.com/codecov/codecov-action/issues/557

permissions:
  contents: read
